### ISSUE TITLE
upstream renamed from `msgpack-python` to `msgpack`

### ISSUE THREAD

**Issue by hhromic** [conda-forge/msgpack-python-feedstock#5]
The name/repository changed upstream from `msgpack-python` to simply `msgpack` in PyPi [1].
Perhaps the entire recipe should be renamed for consistency, e.g. `conda-forge/msgpack`.

> Package name on PyPI was changed to msgpack from 0.5. I upload transitional package (msgpack-python 0.5 which depending on msgpack) for smooth transition from msgpack-python to msgpack.

[1] https://pypi.python.org/pypi/msgpack

**Comment by jakirkham** [comment]
Following up on this. There appears to still be [`msgpack-python` on PyPI]( https://pypi.python.org/pypi/msgpack-python ). In fact there was a `0.5.5` release just yesterday. Was there an announcement to change name today or something?

**Comment by hhromic** [comment]
Yes, the author turned `msgpack-python` into a transitional package that now depends on the official `msgpack` package, as stated in the quoted text from PyPI.
I'm not aware of an announcement, just stumbled upon this and the warnings from the author in the README files while checking the current version of msgpack.
Also the current description of `msgpack-python` in PyPi reads:

> This package is deprecated. Install msgpack instead.

This looks like the commit that started it:

https://github.com/msgpack/msgpack-python/commit/9f4c12f29ce7a6d62423311ab12a031dc79c458a

**Comment by hhromic** [comment]
Looks like changing the conda package name is discouraged:
https://github.com/AnacondaRecipes/msgpack-python-feedstock/issues/1#issuecomment-368248927

It is possible to make the recipe (named `msgpack-python` fetch the package having a different upstream name (`msgpack`) in PyPi? If so, then that should work smoothly.
In Conda, the package name wouldn't change but the recipe will keep tracking the latest version and package upstream.

What do you think?

**Comment by rbubley** [comment]
I presume this could be done with a couple of changes to `meta.yaml`:
`{% set pypi_name = "msgpack" %}`
and
`  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.{{ bundle }}`

But I don't use conda so can't easily test.

**Comment by hhromic** [comment]
A friendly pinging on this :)

It looks like the author of msgpack also updated the `msgpack-python` deprecated module to `5.6.0`, so for now this recipe can be updated out of the box to this version.

However, the solution from @rbubley  should be preferred as the `msgpack` module name is more future-proof.

**Comment by hhromic** [comment]
Looks like [Anaconda](https://github.com/AnacondaRecipes/msgpack-python-feedstock) updated it already to `0.5.6`.
Perhaps this repo could be sync'ed with that one and this issue can be closed now?

**Comment by jakirkham** [comment]
Merged PR ( https://github.com/conda-forge/msgpack-python-feedstock/pull/6 ) from our bot, which should produce packages with the new version.

**Comment by jakirkham** [comment]
@pmlandwehr, can you please weigh in on this?

**Comment by hhromic** [comment]
thanks!
